export const GET_GHIBLI_PEOPLE = "GET-GHIBLI-PEOPLE"; 
export const GET_GHIBLI_PEOPLE_LOADING = "GET-GHIBLI-PEOPLE-LOADING"; 
export const GET_GHIBLI_PEOPLE_ERROR = "GET-GHIBLI-PEOPLE-ERROR"; 

export const GET_GHIBLI_PERSON_FILMS = "GET-GHIBLI-PERSON-FILMS"; 
export const GET_GHIBLI_PERSON_FILMS_LOADING = "GET-GHIBLI-PERSON-FILMS-LOADING"; 
export const GET_GHIBLI_PERSON_FILMS_ERROR = "GET-GHIBLI-PERSON-FILMS-ERROR"; 

export const DISPLAY_GHIBLI_PEOPLE = "DISPLAY-GHIBLI-PEOPLE"; 
export const DISPLAY_GHIBLI_PERSON_FILMS = "DISPLAY-GHIBLI-PERSON-FILMS"; 
export const DISPLAY_CLOSE_GHIBLI_PERSON_FILMS = "DISPLAY-CLOSE-GHIBLI-PERSON-FILMS"; 